### ISSUE TITLE
mutool extract output format not uniform

### ISSUE THREAD

**Issue by ujjvlh** [shreevatsa/pdf-glyph-mapping#1]
I get (with `mupdf-tools 1.18.0-2`, Arch Linux) `.jpg` output by this command instead of `.png`. So we need to explicitly specify the format in the command (if it is possible) for `doit.sh` to work.

**Comment by shreevatsa** [comment]
Oh I see. I think something like `rm image-*.{png,jpg}` will work, except that `rm` may throw an error. Could use `rm -f` but I'm scared of that. :) But found `|| true` that works.
