### ISSUE TITLE
Tjs-*.map files not generated

### ISSUE THREAD

**Issue by ujjvlh** [shreevatsa/pdf-glyph-mapping#3]
On running without making any changes to the code (other than `.png` being replaced with `.jpg` in `doit.sh`), no `Tjs-*.map` files were generated even after `dump-tjs` ran successfully.

**Comment by shreevatsa** [comment]
Oh... was there any other error message? There should be output like:

```
Creating file: Tjs-0019-0.map
```

(with a bit more on the line, after a commit I just added).

**Comment by ujjvlh** [comment]
> Oh... was there any other error message?

No other error message.

>There should be output like:
> 
> ```
> Creating file: Tjs-0019-0.map
> ```

Not found. Seeing these instead:

```
Font (40531, 0) (APZKLW+NotoSansDevanagari-Bold) ToUnicode empty?
Font (40532, 0) (ATMSNB+NotoSansDevanagari) ToUnicode empty?
Font (40533, 0) (ASZHUB+Times-Roman) ToUnicode empty?
Font (40534, 0) (ASLUDF+Times-Bold) ToUnicode empty?
```

Only one `op` is found in `content.operations` for each font. And all of them have `op.operator == "x"` instead of `"endbfchar"` or `"endbfrange"`.

**Comment by ujjvlh** [comment]
Sorry. It was all my fault. Didn't clean the `pdf` beforehand with `qpdf --qdf`.
